# Generated by Django 3.2 on 2021-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.IntegerField(default='')),
                ('name', models.CharField(default='', max_length=100)),
                ('semester', models.IntegerField(default='')),
                ('mobile', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
